name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use node 16
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
