name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 16
        uses: actions/setup-node@1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: run package bundler
        run: npm run build
