name: npm-publish

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Use node 16
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci

      - run: git config --global user.name "microchipgnu"
      - run: git config --global user.email "microchipgnu@gmail.com"

      - run: npm version ${{ github.event.release.tag_name }}

      - name: build
        run: npm run build

      - run: npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_AUTH_TOKEN }}"

      - run: npm publish --tag latest
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - run: git push
        env:
          # The secret is passed automatically. Nothing to configure.
          github-token: ${{ secrets.GITHUB_TOKEN }}
