name: CD
on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          ref: 'release'
          fetch-depth: 0
      - name: Merge main
        run: |
          git --version 
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge origin/main
      - name: Use node 16
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: build
        run: npm run build
      - name: release
        run: |
          git add .
          git commit -m "update release"
          git push
        
